test and logger
htmlacademy-nodejs/153671-typoteka-3 pull request #12
Opened 2020-09-20 16:46 UTC by hopmen

2020-09-23 06:39 UTC, dean992008 requested changes

2020-09-23 06:39 UTC, dean992008 commented on package.json
> +    "pino-multi-stream": "^5.1.1",
Версии зависимостей должно быть зафиксированы: https://up.htmlacademy.ru/nodejs/3/criteries#b24

2020-09-23 06:39 UTC, dean992008 commented on src/service/api/article.e2e.test.js
> +  let mocks = JSON.parse(fs.readFileSync(file));
Если значение не переопределяться мы должны использовать const

2020-09-23 06:39 UTC, dean992008 commented on src/service/api/article.e2e.test.js
> +  let mocks = JSON.parse(fs.readFileSync(file));
Здесь тоже const

2020-09-23 06:39 UTC, dean992008 commented on src/service/lib/logger.js
> +  {level, stream: fs.createWriteStream(appDir + `/logs/logs.txt`)},
Нужно сделать проверку, если нет файла с логами, то создать его, сейчас получаем ошибку в тестах если его нет .

2020-09-23 18:58 UTC, hopmen commented on src/service/api/article.e2e.test.js
> +  let mocks = JSON.parse(fs.readFileSync(file));
следующая строчка `mocks =`  так что не получится

2020-09-24 05:28 UTC, dean992008 commented on package.json
> +    "pino-multi-stream": "^5.1.1",
У `fs-extra` осталось.

2020-09-24 05:29 UTC, dean992008 commented on src/service/api/article.e2e.test.js
> +  let mocks = JSON.parse(fs.readFileSync(file));
Ок

2020-09-24 05:29 UTC, merged